### ISSUE TITLE
Error: FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'

### ISSUE THREAD

**Issue by RobShaw77** [zunzun/FlaskFit#1]
I get an error when I run a simple 3D fit

FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'

I'm not sure where it is expecting the static folder to be or whether that is the issue. Can anyone clarify if this is bug or my own ignorance please?

Thanks
Rob

**Comment by zunzun** [comment]
Investigating now. I will make a fresh clone of the GitHub repository and try to reproduce the error.

James

**Comment by zunzun** [comment]
I did not receive an error on a fresh github clone, see below. Questions:

**1**) Did you change the project directory structure, such as moving the "static" directory?
**2**) Do you have read/write file permissions on the "static" directory?
**3**) Do you see any error on the Flask development console?
**4**) Does the 2D work correctly?

Here is my fresh github clone and console output:

zunzun@zunzun-laptop: github **git clone https://github.com/zunzun/FlaskFit**
Cloning into 'FlaskFit'...
remote: Counting objects: 43, done.
remote: Total 43 (delta 0), reused 0 (delta 0), pack-reused 43
Unpacking objects: 100% (43/43), done.
Checking connectivity... done.
zunzun@zunzun-laptop: /github$ cd FlaskFit/
zunzun@zunzun-laptop: /github/FlaskFit$ python3 FlaskFit.py 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [07/Jun/2017 11:49:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:18] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "POST /simplefitter_3D HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/surface.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/contour.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/abs_error_3D.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/abs_error_hist_3D.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/per_error_3D.png HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2017 11:49:34] "GET /static/per_error_hist_3D.png HTTP/1.1" 200 -

**Comment by RobShaw77** [comment]
James

When I run FlaskFit I get:

%run "E:\FlaskFit-master\FlaskFit.py"
C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\matplotlib\__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 552-341-727
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

Then if I visit http://127.0.0.1:5000/ and run one of the examples the python window then has:

127.0.0.1 - - [08/Jun/2017 08:47:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2017 08:48:01] "POST /simplefitter_3D HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\FlaskFit-master\FlaskFit.py", line 169, in simplefitter_3D_NoFormDataValidation
    TextUtils.SaveCoefficientAndFitStatistics(fitStatisticsFilePath,  equation)
  File "E:\FlaskFit-master\TextUtils.py", line 69, in SaveCoefficientAndFitStatistics
    outputFile = open(in_filePathFitStatistics, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'
127.0.0.1 - - [08/Jun/2017 08:48:01] "GET /simplefitter_3D?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2017 08:48:01] "GET /simplefitter_3D?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2017 08:48:01] "GET /simplefitter_3D?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2017 08:48:01] "GET /simplefitter_3D?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2017 08:48:01] "GET /simplefitter_3D?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

Does that make sense?

In terms of your questions:
1) No. My static directory is a subfolder of where the FlashFit.py file is, which is E:\FlaskFit-master
2) Yes
3) Is this what I've put above?
4) No. I get the same error but with 2D instead of 3D.

![image](https://user-images.githubusercontent.com/29256807/26917849-b2c2aac4-4c27-11e7-9804-c2474c2ee83c.png)

I've pasted an image of the Chrome window with the error that shows there.

Thanks for you help

Rob

**Comment by zunzun** [comment]
Excellent reply. Analysing now.

**Comment by zunzun** [comment]
In the rather copious debug output I see:
File "E:\FlaskFit-master\TextUtils.py", line 69, in SaveCoefficientAndFitStatistics
outputFile = open(in_filePathFitStatistics, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'

which tells me that Python cannot create, for writing, the fit statistics file.

As a test, would you please edit the end of
File "E:\FlaskFit-master\TextUtils.py", line 69
from "w"
outputFile = open(in_filePathFitStatistics, **'w'**)
to "wt"
outputFile = open(in_filePathFitStatistics, **'wt'**)
and try again?

**Comment by RobShaw77** [comment]
Ok. I made that change. I now get:
  File "E:\FlaskFit-master\TextUtils.py", line 69, in SaveCoefficientAndFitStatistics
    outputFile = open(in_filePathFitStatistics, 'wt')
FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'

and in the Chrome window:

File "E:\FlaskFit-master\TextUtils.py", line 69, in SaveCoefficientAndFitStatistics
outputFile = open(in_filePathFitStatistics, 'wt')
FileNotFoundError: [Errno 2] No such file or directory: 'static/fitstatistics_3D.txt'

So it is definitely picking up the change to TextUtil.py.

**Comment by zunzun** [comment]
Thank you.  Your test shows that opening the file with  "w" or "wt" is not causing the problem.

As a second test could you please try to create a file using the following Python code? Please run this from the same directory as the FlaskFit.py file.

f = open('static/test.txt', 'w')
f.close()

**Comment by RobShaw77** [comment]
That gave the same error. However, if I run it without the subdirectory (just text.txt) it works fine. I also tried the test file in my Documents folder and with other subfolders and get the same error. So it seems to be something to do with referencing subdirectories.

**Comment by zunzun** [comment]
Thanks to your testing, I understand the cause of the error. There is some difference in opening a file in a subdirectory, as I have coded, between Windows and Linux. I will find a method that works on both operating systems, and then ask you to test that similarly to what you have just done.

**Comment by RobShaw77** [comment]
Thanks. I just ran

import os
os.chdir('E:\FlaskFit-master\static')
cwd = os.getcwd()
print(cwd)
f = open('test.txt', 'w')
f.close()

and this works fine.

**Comment by zunzun** [comment]
This test shows that my existing code for _relative_ path names does not work on Windows, but _absolute_ path names do work.  I will update FlaskFit to find the current directory and use that to create an absolute pathname. I know how to do that, and it will work on all operating systems.

**Comment by zunzun** [comment]
Would you please run the following Python code from the same directory as the FlaskFit.py file?

import os
os.path.realpath('static')

It should display the absolute path to the "static" directory. If this works as expected, I am ready to make the necessary code changes to fix the problem.

**Comment by zunzun** [comment]
I finished the code changes, the latest GitHub code should now work correctly.

**Comment by RobShaw77** [comment]
Hi. Thanks for all you've done on this. But is still not working :(

I get the error: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Rob Shaw\\static\\fitStatistics_3D.txt'

This is on the same line 69. I've set the working directory to e:\flask-fit.

However, if I open fileinfo.py and add print(fitStatisticsFilePath_3D) after line 16 it correctly outputs E:\FlaskFit-master\static\fitStatistics_3D.txt

So I don't know where it is getting c:\users\Rob Shaw from since my user folder on the E: drive anyway.

This is the full traceback:

Traceback (most recent call last):
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rob Shaw\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\FlaskFit-master\FlaskFit.py", line 161, in simplefitter_3D_NoFormDataValidation
    TextUtils.SaveCoefficientAndFitStatistics(FileInfo.fitStatisticsFilePath_3D,  equation)
  File "E:\FlaskFit-master\TextUtils.py", line 69, in SaveCoefficientAndFitStatistics
    outputFile = open(in_filePathFitStatistics, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Rob Shaw\\static\\fitStatistics_3D.txt'

**Comment by RobShaw77** [comment]
James

Ignore that last post. I just reran it and it worked perfectly. [weird!]

Many thanks for all your help 👍 

Rob

**Comment by zunzun** [comment]
Excellent result. Thanks to your reporting of the problem, this should now work for other users of Windows.  I will also make the same changes to my BottleFit and CherryPyFit projects.
